swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
schemes:
  - https
paths:
  /sample/api/start:
    post:
      summary: ""
      description: ""
      operationId: "start"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "body"
          in: "body"
          description: ""
          schema:
            $ref: "#/definitions/StartRequest"
      responses:
        200:
          description: OK
definitions:
  StartRequest:
    type: "object"
    properties:
      id:
        type: "string"
