swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
schemes:
  - https
paths:
  /create:
    post:
      summary: ""
      description: ""
      operationId: "create"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "body"
          in: "body"
          description: ""
          schema:
            $ref: "#/definitions/CreateRequest"
      responses:
        200:
          description: OK
definitions:
  CreateRequest:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
