AWSTemplateFormatVersion: '2010-09-09'
Resources:
  lambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      RoleName: "sample-lambda-role"
  lambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:*"
              - "s3:*"
              - "sqs:*"
              - "lambda:*"
              - "xray:*"
              - "logs:*"
            Resource: "*"
      PolicyName: "sample-lambda-policy"
      Roles:
        - !Ref lambdaRole
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: sample-vpc
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'sample'
      VpcId: !Ref vpc
  securityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref securityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref securityGroup
  routeTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref vpc
      Tags:
        - Key: Name
          Value: sample-routetable
  subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.64.0/20
      VpcId: !Ref vpc
  subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.128.0/20
      VpcId: !Ref vpc
  subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnet1
      RouteTableId: !Ref routeTable
  subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnet2
      RouteTableId: !Ref routeTable
  s3:
    Type: AWS::S3::Bucket
    Properties:
      DeletionPolicy: Retain
      Tags:
        - Key: Name
          Value: sample-bucket
  sqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: sample
  sqsVpcEndPoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref vpc
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref subnet1
        - !Ref subnet2
      SecurityGroupIds:
        - !Ref securityGroup
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .sqs
      VpcEndpointType: Interface
  s3VpcEndPoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref vpc
      RouteTableIds:
        - !Ref routeTable
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .s3
  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: "A sample API"
      EndpointConfiguration:
        Types:
          - PRIVATE
      Name: "SampleAPI"
      Policy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Deny"
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: "execute-api:/*/https/*"
            Condition:
              StringNotEquals:
                "aws.sourceVpc": !Ref vpc
          - Effect: "Allow"
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: "execute-api:/*/https/*"
  dbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Group
      SubnetIds:
        - !Ref subnet1
        - !Ref subnet2
  rdsCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterParameterGroupName: default.aurora-postgresql9.6
      Engine: aurora-postgresql
      EngineVersion: 9.6.12
      MasterUsername: test
      MasterUserPassword: test1234
      Port: 5432
      DBSubnetGroupName: !Ref dbSubnetGroup
Outputs:
  LambdaRole:
    Value:
      Fn::GetAtt:
        - lambdaRole
        - Arn
    Export:
      Name: sample-lambda-role
  apiGateway:
    Value: !Ref apiGateway
    Export:
      Name: sample-apigateway
  RootResourceId:
    Value:
      Fn::GetAtt:
        - apiGateway
        - RootResourceId
    Export:
      Name: sample-apigateway-root-id
  SecurityGroup:
    Value: !Ref securityGroup
    Export:
      Name: sample-security-group
  Subnet1:
    Value: !Ref subnet1
    Export:
      Name: sample-subnet1
  Subnet2:
    Value: !Ref subnet2
    Export:
      Name: sample-subnet2
  Sqs:
    Value:
      Fn::GetAtt:
        - sqs
        - QueueName
    Export:
      Name: sample-queue
  RdsEndpoint:
    Value:
      Fn::GetAtt:
        - rdsCluster
        - Endpoint.Address
    Export:
      Name: sample-rds-endpoint
  RdsReadonlyEndpoint:
    Value:
      Fn::GetAtt:
        - rdsCluster
        - ReadEndpoint.Address
    Export:
      Name: sample-rds-readonly-endpoint
  S3:
    Value: !Ref s3
    Export:
      Name: sample-bucket