service: sample-api

provider:
  name: aws
  runtime: python3.7
  apiGateway:
    restApiId:
      "Fn::ImportValue": "sample-apigateway"
    restApiRootResourceId:
      "Fn::ImportValue": "sample-apigateway-root-id"

package:
  artifact: ../../target/api.zip

functions:
  sample-api:
    handler: hello.lambda_handler
    layers:
      - "Fn::ImportValue": "sample-lambda-layer-infra"
    events:
      - http:
          path: sample
          method: post

