service: sample-api-layer

provider:
  name: aws

layers:
  infra:
    package:
      artifact: ../../target/infrastructure.zip

resources:
  Outputs:
    InfraLambdaLayerQualifiedArn:
      Value:
        "Ref": InfraLambdaLayer
      Export:
        Name: sample-lambda-layer-infra
