service: sample-api-psycopg2

provider:
  name: aws

layers:
  psycopg2:
    package:
      artifact: ../../target/psycopg2.zip
    retain: false

resources:
  Outputs:
    Psycopg2LambdaLayerQualifiedArn:
      Export:
        Name: sample-lambda-layer-psycopg2
